### ISSUE TITLE
webdriver_manager pointing to browser version instead of driver version?

### ISSUE THREAD

**Issue by Jonathan-Garcia1** [gaspa93/googlemaps-scraper#51]
(google_maps_scrape) jg@J-MacBook-Pro googlemaps-scraper % python scraper.py --N 50 --i urls_1.txt
Traceback (most recent call last):
  File "/Users/folder/googlemaps-scraper/scraper.py", line 43, in <module>
    with GoogleMapsScraper(debug=args.debug) as scraper:
  File "/Users/folder/googlemaps-scraper/googlemaps.py", line 31, in __init__
    self.driver = self.__get_driver()
  File "/Users/folder/googlemaps-scraper/googlemaps.py", line 377, in __get_driver
    input_driver = webdriver.Chrome(executable_path=ChromeDriverManager(log_level=0).install(), options=options)
  File "/usr/local/anaconda3/envs/google_maps_scrape/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "/usr/local/anaconda3/envs/google_maps_scrape/lib/python3.10/site-packages/webdriver_manager/manager.py", line 23, in _get_driver_path
    driver_version = driver.get_version()
  File "/usr/local/anaconda3/envs/google_maps_scrape/lib/python3.10/site-packages/webdriver_manager/driver.py", line 41, in get_version
    return self.get_latest_release_version()
  File "/usr/local/anaconda3/envs/google_maps_scrape/lib/python3.10/site-packages/webdriver_manager/driver.py", line 74, in get_latest_release_version
    validate_response(resp)
  File "/usr/local/anaconda3/envs/google_maps_scrape/lib/python3.10/site-packages/webdriver_manager/utils.py", line 80, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_118.0.5993
(google_maps_scrape) jg@J-MacBook-Pro  googlemaps-scraper %

**Comment by meggnotec** [comment]
I have the same issue. Any solutions?

**Comment by Jonathan-Garcia1** [comment]
I found what was causing it. it turns out that I had updated my chrome browser version and the latest chromedriver did not match versions. In such cases you can either wait for the updated driver version to be updated or like I did, hard coded a browser and driver path. I installed chrome beta browser because it had a matching driver versions available.  This lead me to rewrite the get_driver function entirely. 
![image](https://github.com/gaspa93/googlemaps-scraper/assets/136507954/424fc7b9-1f49-4114-ae01-e32dab728b00)

you can check out my project here, where I used a modified version of the scraper in combination with tor to scrape google maps. 

https://github.com/Somerville-2023/New-York-health-Inspection-Prediction/blob/main/john-folder/scraper_gmaps/googlemaps.py
